// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: createUser :one
INSERT into users (
    username, 
    hashed_password, 
    full_name, 
    email
) VALUES ( ?1, ?2, ?3, ?4
) RETURNING username, hashed_password, full_name, email, password_changed_at, created_at, is_email_verified
`

func (q *Queries) createUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
	)
	return i, err
}
